@url = http://localhost:8088

### hello
GET {{url}}/hello


### task
POST {{url}}/task
Content-Type: application/json

{
  "Title": "task665",
  "Description": "description31"
}

### GET task by ID
GET {{url}}/task/4

### GET all tasks
GET {{url}}/tasks

### DELETE task by ID
DELETE {{url}}/task/2