### hello
GET http://localhost:8080/hello


### task
POST http://localhost:8080/task
Content-Type: application/json

{
  "Title": "task55",
  "Description": "description31"
}

### GET task by ID
GET http://localhost:8080/task/2

### GET all tasks
GET http://localhost:8080/tasks

### DELETE task by ID
DELETE http://localhost:8080/task/2